// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFjui3dOIcvsT2VB1QEXt8XTwoEscl2I',
    appId: '1:1049888034267:web:1543fbdd2781e88fdeabfe',
    messagingSenderId: '1049888034267',
    projectId: 'chat-cd5e0',
    authDomain: 'chat-cd5e0.firebaseapp.com',
    databaseURL: 'https://chat-cd5e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-cd5e0.firebasestorage.app',
    measurementId: 'G-2R08BRBDLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ_KImISNhTc8w-MwXfDBjRPpSbKILF7c',
    appId: '1:1049888034267:android:7854a9b6d491b654deabfe',
    messagingSenderId: '1049888034267',
    projectId: 'chat-cd5e0',
    databaseURL: 'https://chat-cd5e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-cd5e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhC8FDpEtOdpPcnQpCrubN0AMStQGQt8',
    appId: '1:1049888034267:ios:04aedd1066fafb50deabfe',
    messagingSenderId: '1049888034267',
    projectId: 'chat-cd5e0',
    databaseURL: 'https://chat-cd5e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-cd5e0.firebasestorage.app',
    iosClientId: '1049888034267-sdn7fsnkdv0bilimk825924gq8n8bpu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhC8FDpEtOdpPcnQpCrubN0AMStQGQt8',
    appId: '1:1049888034267:ios:04aedd1066fafb50deabfe',
    messagingSenderId: '1049888034267',
    projectId: 'chat-cd5e0',
    databaseURL: 'https://chat-cd5e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-cd5e0.firebasestorage.app',
    iosClientId: '1049888034267-sdn7fsnkdv0bilimk825924gq8n8bpu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANLYO2x3UlU3XnsZ62JpF5OI-Z_NtUD00',
    appId: '1:1049888034267:web:cf5efd8608581742deabfe',
    messagingSenderId: '1049888034267',
    projectId: 'chat-cd5e0',
    authDomain: 'chat-cd5e0.firebaseapp.com',
    databaseURL: 'https://chat-cd5e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-cd5e0.firebasestorage.app',
    measurementId: 'G-K6LX0VS5W3',
  );
}
